# Deliverable 3. Create a Travel Itinerary Map.
----
1. Import the vacation CSV file. 
2. From the map above with pick 4 cities that are in close proximity (on the same continent) that the customer would travel to and create a directions layer map.
3. For the "travel_mode" use either "DRIVING", "BICYCLING", or "WALKING".
4. Take a screenshot of the route and save it. 
5. Then create a marker layer for the four cities. Each city will should have a pop-up marker that contains
    - The hotel name
    - The city
    - The country
    - The current weather description and the maximum temperature
---

## Make sure the initial dependencies and the Google API key are imported.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

In [2]:
# Configure gmaps
gmaps.configure(api_key=g_key)

## From your `Vacation_Search` folder from Deliverable 2, import the `WeatherPy_vacation.csv` file as a DataFrame named `vacation_df`

In [3]:
# Read the WeatherPy_vacation.csv into a DataFrame
vacation_df = pd.read_csv("../Vacation_search/WeatherPy_vacation.csv")
vacation_df.drop(columns="Unnamed: 0", axis=1, inplace=True)
# Display sample data
vacation_df

City Country      Lat       Lng  Max Temp  Humidity  Cloudiness  \
0          Atuona      PF  -9.8000 -139.0333     76.39        79          27   
1           Vaini      TO -21.2000 -175.2000     75.36        88          75   
2          Faanui      PF -16.4833 -151.7500     77.95        75           6   
3    Puerto Ayora      EC  -0.7393  -90.3518     75.16        92          81   
4           Kapaa      US  22.0752 -159.3190     82.72        71           0   
..            ...     ...      ...       ...       ...       ...         ...   
203     Les Cayes      HT  18.2000  -73.7500     83.77        66          11   
204         Alofi      NU -19.0595 -169.9187     78.69        73          75   
205   Pedro Carbo      EC  -1.8333  -80.2333     86.70        46          89   
206       Mayumba      GA  -3.4320   10.6554     76.10        85          99   
207        Palmer      US  42.1584  -72.3287     76.55        48          40   

     Wind Speed Current Description  \
0         19.93          light rain   
1         10.36       broken clouds   
2         22.08          light rain   
3          8.99       broken clouds   
4         10.36           clear sky   
..          ...                 ...   
203        5.46          few clouds   
204       14.97       broken clouds   
205        9.95     overcast clouds   
206        6.46     overcast clouds   
207        9.22    scattered clouds   

                                        Hotel Name  
0                                      Villa Enata  
1                              Keleti Beach Resort  
2               Bora-Bora Pearl Beach Resort & Spa  
3                        Finch Bay Galapagos Hotel  
4              Sheraton Kauai Coconut Beach Resort  
..                                             ...  
203                                   Villa Orphee  
204                                  Taloa Heights  
205  Centro turístico y hostería oasis pedro carbo  
206                                  LIKWALE LODGE  
207                                Wedgewood Motel  

[208 rows x 10 columns]

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [4]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## In this step, you will set-up the pop-up markers. Review the code to create a marker layer map of the vacation search results. This code is the same as in Deliverable 2.

In [5]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [6]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

## From the vacation search map, *choose four cities* that a customer might want to visit. They should be close together and in the same country.

In [7]:
# Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df["City"]=="Rodrigues Alves"]
vacation_end = vacation_start
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="Porto Walter"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Tarauaca"]
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Benjamin Constant"]

In [46]:
# Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df["City"]=="Half Moon Bay"]
vacation_end = vacation_start
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="Pacific Grove"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Pahrump"]
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Fallon"]

## Use the `to_numpy()` function and list indexing to write code to retrieve the latitude-longitude pairs as tuples from each city DataFrame.

In [48]:
# Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = start
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]

In [49]:
display(start, end, stop1, stop2, stop3)

array([  37.4636, -122.4286])

array([  37.4636, -122.4286])

array([  36.6177, -121.9166])

array([  36.2083, -115.9839])

array([  39.4735, -118.7774])

## Use the [gmaps documentation](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#directions-layer) to create a directions layer map using the variables from the previous step. Where the starting and ending city are the same city, the `waypoints` are the three other cities, and the `travel_mode` is either `"DRIVING"`, `"BICYCLING"`, or `"WALKING"`.

In [50]:
# Define a new figure object
fig = gmaps.figure()

# Create a direction layer map using the start and end latitude-longitude pairs, and stop1, stop2, and stop3 as the waypoints.
# The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
vacation_itinerary = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode='DRIVING')

# Add the layer to the map
fig.add_layer(vacation_itinerary)

# Display the map
fig

Figure(layout=FigureLayout(height='420px'))

## Use the provided `concat()` function code snippet to combine the four separate city DataFrames into one DataFrame.

In [57]:
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat(
    [
        vacation_start,
        vacation_stop1,
        vacation_stop2,
        vacation_stop3
    ],
    ignore_index = True
)

# Display sample data
itinerary_df

City Country      Lat       Lng  Max Temp  Humidity  Cloudiness  \
0  Half Moon Bay      US  37.4636 -122.4286     85.05        69           0   
1  Pacific Grove      US  36.6177 -121.9166     77.38        82           0   
2        Pahrump      US  36.2083 -115.9839     89.65        18           0   
3         Fallon      US  39.4735 -118.7774     81.45        13          20   

   Wind Speed Current Description                        Hotel Name  
0        9.22           clear sky   The Ritz-Carlton, Half Moon Bay  
1        6.91                haze                  Lovers Point Inn  
2        4.00           clear sky        Best Western Pahrump Oasis  
3        0.00          few clouds  Best Western Fallon Inn & Suites

## Refactor the code from Step 6 to create a new marker layer map of the cities on the travel route.

In [58]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [61]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Define a new figure object
fig = gmaps.figure()

# Add the layer to the map
fig.add_layer(marker_layer)

# Display the map
fig

Figure(layout=FigureLayout(height='420px'))